# Generated by Django 3.0.1 on 2020-01-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0011_auto_20200128_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerStockInfoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_capacity', models.CharField(max_length=100)),
                ('item_rate', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('item_quality', models.CharField(max_length=100)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerInfoTable')),
            ],
            options={
                'unique_together': {('item_rate', 'item_type', 'item_quality', 'dealer_id')},
            },
        ),
    ]
