# Generated by Django 3.0.1 on 2020-01-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerstockinfotable',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
