# Generated by Django 3.0.1 on 2020-02-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfotable',
            name='orderReviewStarRating',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='orderinfotable',
            name='orderReviewText',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderinfotable',
            name='orderWithPromocode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
