# Generated by Django 3.0.1 on 2020-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createOrder', '0002_auto_20200216_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfotable',
            name='orderStatus',
            field=models.CharField(default='Not Confirmed By Dealer', max_length=50),
        ),
    ]
