# Generated by Django 3.0.1 on 2020-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerinfotable',
            name='password',
            field=models.CharField(default='D3YTFNI9D9CNXK42ULZNI51178H8MVQPCRCMFSN8NH2HNI74BG', max_length=50),
        ),
    ]
