# Generated by Django 3.0.1 on 2020-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerinfotable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerinfotable',
            name='password',
            field=models.CharField(default='NMXOBTRFB3OC3Z0M19OKBT8J3W1VJQ9E7HRGH3VSZU82M5WOJ8', max_length=50),
        ),
    ]
