# Generated by Django 3.0.1 on 2020-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_auto_20200125_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerinfotable',
            name='password',
            field=models.CharField(default='E3IA6INZKFH0HDJT7CEQKJR1JYS6THWWD4AY0RSQFJXUUBWP6G', max_length=50, unique=True),
        ),
    ]
