# Generated by Django 3.0.1 on 2020-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20200125_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerinfotable',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dealerinfotable',
            name='password',
            field=models.CharField(default='CMID1X8GAY31LRORSG0W49QDKGF2UUGO5UU1STXHEDPWYSVQK0', max_length=50, unique=True),
        ),
    ]
