# Generated by Django 3.0.1 on 2020-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_auto_20200125_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerinfotable',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dealerinfotable',
            name='imageURL',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='dealerinfotable',
            name='password',
            field=models.CharField(default='LPKKX', max_length=5),
        ),
    ]
