# Generated by Django 3.0.1 on 2020-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_auto_20200125_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerinfotable',
            name='password',
            field=models.CharField(default='EQD5J', max_length=5),
        ),
    ]
