# Generated by Django 3.0.1 on 2020-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfotable',
            name='password',
            field=models.CharField(default='QPUTPJGYZUBL4APHV3KSV23479M828QBG2HU7HTIAJV6KGKBQB', max_length=50),
        ),
    ]
