# Generated by Django 3.0.1 on 2020-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfotable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfotable',
            name='password',
            field=models.CharField(default='YKHSFL1YGH7XJ62UCOMDFVPFTKWL1R5IQIIA7OA7VLGTV9P1OG', max_length=50),
        ),
    ]
