# Generated by Django 3.0.1 on 2020-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200125_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfotable',
            name='password',
            field=models.CharField(default='RT8YW8FONE3Z8JNVXG3TYAMCJRCSJ2TXVFT9Z1N9YVCSN4QBQC', max_length=50, unique=True),
        ),
    ]
