# Generated by Django 3.0.1 on 2020-01-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200125_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfotable',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfotable',
            name='password',
            field=models.CharField(default='GDUGUKJL212TDQCNS85ILIXZU4LIYOVYXO9CHYW20ZGIVX87TH', max_length=50, unique=True),
        ),
    ]
