# Generated by Django 3.0.1 on 2020-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200125_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfotable',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfotable',
            name='password',
            field=models.CharField(default='V132Y', max_length=5),
        ),
    ]
